# Vai nightfall

[bar/nightfall]
width = 100%
height = 30
fixed-center = true

background = #CC080B12
foreground = #E6E6E6

line-size = 2
border-size = 0

padding-left = 1
padding-right = 1

module-margin = 1

font-0 = JetBrains Mono:size=10;2

modules-left = gentoo workspaces
modules-center = title
modules-right = volume memory battery time

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

[module/gentoo]
type = custom/text
content = GENTOO
content-foreground = #B39DFF
content-padding = 1

[module/workspaces]
type = internal/i3
format = <label-state>

label-focused = %name%
label-focused-foreground = #B39DFF
label-focused-background = #202634
label-focused-padding = 1

label-unfocused = %name%
label-unfocused-foreground = #A6ADC8
label-unfocused-padding = 1

label-visible = %name%
label-visible-foreground = #A6ADC8
label-visible-padding = 1

label-urgent = %name%
label-urgent-foreground = #F7768E
label-urgent-padding = 1


[module/title]
type = custom/text
content = Gentoo Linux
content-foreground = #B39DFF


[module/wifi]
type = internal/network
interface = wlp2s0
interval = 3

format-connected = WIFI <label-connected>
label-connected = %essid%

format-disconnected = WIFI offline
label-disconnected-foreground = #F7768E


[module/volume]
type = internal/pulseaudio
format-volume = VOL <label-volume>
label-volume = %percentage%%

format-muted = VOL muted
label-muted-foreground = #F7768E


[module/memory]
type = internal/memory
interval = 3
format = RAM <label>
label = %percentage_used%%


[module/battery]
type = internal/battery
battery = BAT0
adapter = ADP0
poll-interval = 5

format-charging = BAT <label-charging>
format-discharging = BAT <label-discharging>
format-full = BAT <label-full>

label-charging = %percentage%%
label-discharging = %percentage%%
label-full = %percentage%%

[module/time]
type = internal/date
interval = 1
date = %H:%M
label = %date%
